export PATH="$PATH:/usr/bin"
export PATH="/usr/local/Cellar/git/2.15.1/bin:$PATH"
export PATH="/usr/local/Cellar/git/2.15.1/bin:$PATH"
export PATH="/usr/local/bin:$PATH"
export PATH="$PATH:/bin"
export PATH="$PATH:/usr/sbin"
export PATH="/usr/local/sbin:$PATH"
export PATH="$PATH:/sbin"
export PATH="$PATH:/opt/local/bin"
export PATH="$NVM_BIN:$PATH"
export PATH="./node_modules/.bin:$PATH"
export PATH="./node_modules/.bin:$PATH"
export PATH="./vendor/bin:$PATH"
export PATH="$HOME/.composer/vendor/bin:$PATH"
export PATH="$HOME/.rbenv/bin:$PATH"

# Go
export GOPATH=$HOME/go
export PATH="$GOPATH/bin:$PATH"
